### ISSUE TITLE
Issue with version container-transform 1.0 and docker-compose file version 1

### ISSUE THREAD

**Issue by chussenot** [micahhausler/container-transform#38]
My docker-compose.yml file

``` yaml
rumifico:
  image: id.dkr.ecr.us-east-1.amazonaws.com/rumifico:latest
  cpu_shares: 1024
  mem_limit: 2147483648b
  environment:
    RACK_ENV: xolo
  ports:
   - "1701"
```

When i transform and send the output to aws with version 0.6.1, it's OK :+1: 

``` bash
sudo -H pip install --upgrade "container-transform==0.6.1"
cat docker-compose.yml | container-transform  -v > tmp/task.json
aws ecs register-task-definition --cli-input-json file://tmp/task.json --family rumifico-master
{
    "taskDefinition": {
        "status": "ACTIVE",
        "family": "rumifico-master",
        "requiresAttributes": [
            {
                "name": "com.amazonaws.ecs.capability.ecr-auth"
            }
        ],
        "volumes": [],
        "taskDefinitionArn": "arn:aws:ecs:us-east-1:520600400730:task-definition/rumifico-master:18",
        "containerDefinitions": [
            {
                "environment": [
                    {
                        "name": "RACK_ENV",
                        "value": "xolo"
                    }
                ],
                "name": "rumifico",
                "mountPoints": [],
                "image": "520600400730.dkr.ecr.us-east-1.amazonaws.com/rumifico:latest",
                "cpu": 1024,
                "portMappings": [
                    {
                        "protocol": "tcp",
                        "containerPort": 1701,
                        "hostPort": 0
                    }
                ],
                "memory": 2048,
                "essential": true,
                "volumesFrom": []
            }
        ],
        "revision": 18
    }
}
```

And with version 1.0.0

``` bash
sudo -H pip install --upgrade "container-transform==1.0.0"
cat docker-compose.yml | container-transform  -v > tmp/task.json
Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 7, in <module>
    from container_transform.client import transform
  File "/Library/Python/2.7/site-packages/container_transform/__init__.py", line 3, in <module>
    from .converter import Converter
  File "/Library/Python/2.7/site-packages/container_transform/converter.py", line 3, in <module>
    from .compose import ComposeTransformer
  File "/Library/Python/2.7/site-packages/container_transform/compose.py", line 6, in <module>
    from .transformer import BaseTransformer
  File "/Library/Python/2.7/site-packages/container_transform/transformer.py", line 25
    class BaseTransformer(object, metaclass=ABCMeta):
                                           ^
SyntaxError: invalid syntax
make: *** [ecs-task-definition] Error 1
```

**Comment by micahhausler** [comment]
Hey, with version 1.0, I've removed support for python 2, but published a Docker image. You can run:

```
docker pull micahhausler/container-transform
cat docker-compose.yml | docker run --rm -i micahhausler/container-transform
```

**Comment by cpvandehey** [comment]
Docker compose version 3 does not support mem_limit attribute anymore.. Does this mean that compose-transform will not work with version 3?
