### ISSUE TITLE
Doesn't seem to support and enumeration of ports for DBs

### ISSUE THREAD

**Issue by occasl** [micahhausler/container-transform#43]
I have a docker-compose.yml that looks as follows:

```
version: '2'
services:
  oracle:
    image: wnameless/oracle-xe-11g:latest
    hostname: adb
    ports:
      - "49160:22"
      - "49161:1521"
      - "49080:8080"
    environment:
      - processes=200
    volumes:
      - data:/u01/app/oracle
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - .:/app
    depends_on:
     - oracle
    links:
     - oracle
volumes:
  data: {}
```

When I run the command to convert this it fails on what it calls an enum:

```
➜  cas-acronyms-db git:(develop) ✗  cat docker-compose-aws.yml | container-transform -v
Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 7, in <module>
    from container_transform.client import transform
  File "/usr/local/lib/python2.7/site-packages/container_transform/__init__.py", line 3, in <module>
    from .converter import Converter
  File "/usr/local/lib/python2.7/site-packages/container_transform/converter.py", line 1, in <module>
    from .schema import TransformationTypes, ARG_MAP
  File "/usr/local/lib/python2.7/site-packages/container_transform/schema.py", line 1, in <module>
    from enum import Enum
ImportError: No module named enum
```

I tried using the original docker-compose version 1 and the same issue.

**Comment by micahhausler** [comment]
Hey sorry this project is python3 only or you can run the containerized version.

**Comment by occasl** [comment]
No problem. I installed Python 3.5 and installed your package using pip3. It might be helpful to update that in your docs so it's clear to use pip3 to install. Nice utility!
