### ISSUE TITLE
can't run container-transform (KeyError: 'M')

### ISSUE THREAD

**Issue by gustavosoares** [micahhausler/container-transform#56]
Hi, I am trying to use container-transform to convert a working docker-compose file to ecs format and I am getting

cat docker-compose.yml | docker run --rm -i micahhausler/container-transform

Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 9, in <module>
    load_entry_point('container-transform==1.1.4', 'console_scripts', 'container-transform')()
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/client.py", line 64, in transform
    output = converter.convert(verbose)
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/converter.py", line 57, in convert
    output_transformer
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/converter.py", line 100, in _convert_container
    output[output_name] = emit_func(ingest_func(container.get(input_name)))
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/compose.py", line 192, in ingest_memory
    return bit_shift[unit]['func'](number, bit_shift[unit]['shift'])
KeyError: 'M'

any ideas?

**Comment by micahhausler** [comment]
It looks like you're using upper case memory units. For now, switch to lowercase (`128m` instead of `128M`). I'll add a fix that will automatically do this
