### ISSUE TITLE
Error while running `container-transform -h`

### ISSUE THREAD

**Issue by ShahBinoy** [micahhausler/container-transform#60]
root@shahb-e7440:/# python --version
Python 2.7.12
root@shahb-e7440:/# pip -V
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
root@shahb-e7440:/# container-transform -h
Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 9, in <module>
    load_entry_point('container-transform==1.1.4', 'console_scripts', 'container-transform')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/container_transform/**init**.py", line 3, in <module>
    from .converter import Converter
  File "/usr/local/lib/python2.7/dist-packages/container_transform/converter.py", line 3, in <module>
    from .compose import ComposeTransformer
  File "/usr/local/lib/python2.7/dist-packages/container_transform/compose.py", line 6, in <module>
    from .transformer import BaseTransformer
  File "/usr/local/lib/python2.7/dist-packages/container_transform/transformer.py", line 37
    class BaseTransformer(object, metaclass=ABCMeta):
                                           ^
SyntaxError: invalid syntax

**Comment by micahhausler** [comment]
Python 2 is not supported.
