### ISSUE TITLE
Python error when trying to transform docker-compose

### ISSUE THREAD

**Issue by Moep90** [micahhausler/container-transform#62]
I'm installing it as shown in docs:

```
pip install container-transform
Collecting container-transform
  Downloading container-transform-1.1.4.tar.gz
Requirement already satisfied: PyYAML<4,>=3.10 in /Library/Python/2.7/site-packages (from container-transform)
Requirement already satisfied: Jinja2>=2.7.0 in /Library/Python/2.7/site-packages (from container-transform)
Collecting click>=3.3 (from container-transform)
  Downloading click-6.6-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 2.2MB/s
Requirement already satisfied: MarkupSafe in /Library/Python/2.7/site-packages (from Jinja2>=2.7.0->container-transform)
Building wheels for collected packages: container-transform
  Running setup.py bdist_wheel for container-transform ... done
  Stored in directory: /Users/danny.heinrich/Library/Caches/pip/wheels/f3/44/e8/c8034b152a761279d741568098c3eee2ccbbcf776a49c161a8
Successfully built container-transform
Installing collected packages: click, container-transform
Successfully installed click-6.6 container-transform-1.1.4
```

It installs successfully but after running it as shown in docs it gives me:

```
cat docker-compose.yml |container-transform -v
Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 7, in <module>
    from container_transform.client import transform
  File "/usr/local/lib/python2.7/site-packages/container_transform/__init__.py", line 3, in <module>
    from .converter import Converter
  File "/usr/local/lib/python2.7/site-packages/container_transform/converter.py", line 3, in <module>
    from .compose import ComposeTransformer
  File "/usr/local/lib/python2.7/site-packages/container_transform/compose.py", line 6, in <module>
    from .transformer import BaseTransformer
  File "/usr/local/lib/python2.7/site-packages/container_transform/transformer.py", line 36
    class BaseTransformer(object, metaclass=ABCMeta):
                                           ^
SyntaxError: invalid syntax
```

System: macOS Sierra
Version: 10.12.1
HW: MacBook pro early 2015

**Comment by micahhausler** [comment]
This is a python 3 only project. You can either install with python 3 or use the docker image
