### ISSUE TITLE
Error when trying to translate the k8s example to Marathon

### ISSUE THREAD

**Issue by tobilg** [micahhausler/container-transform#67]
When trying to use the k8s example as input, and specifying Marathon as output like this

    docker run --rm -v /tmp:/data/ micahhausler/container-transform -i kubernetes -o marathon k8s.yml

I see the following error:

```
docker run --rm -v /tmp:/data/ micahhausler/container-transform -i kubernetes -o marathon k8s.yml
Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 9, in <module>
    load_entry_point('container-transform==1.1.4', 'console_scripts', 'container-transform')()
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/client.py", line 64, in transform
    output = converter.convert(verbose)
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/converter.py", line 57, in convert
    output_transformer
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/converter.py", line 90, in _convert_container
    output[output_name] = emit_func(ingest_func(container.get(input_name)))
  File "/usr/local/lib/python3.5/site-packages/container_transform-1.1.4-py3.5.egg/container_transform/kubernetes.py", line 321, in ingest_cpu
    cpu = float(int(cpu[:-1]) / 1000)
ValueError: invalid literal for int() with base 10: '100.0'
```

**Comment by tobilg** [comment]
Closing due to no reply.
