### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ghost** [micahhausler/container-transform#83]
after the python install :
Traceback (most recent call last):
  File "/usr/local/bin/container-transform", line 9, in <module>
    load_entry_point('container-transform==1.1.5', 'console_scripts', 'container-transform')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/container_transform/__init__.py", line 3, in <module>
    from .converter import Converter
  File "/Library/Python/2.7/site-packages/container_transform/converter.py", line 1, in <module>
    from .schema import TransformationTypes, ARG_MAP
  File "/Library/Python/2.7/site-packages/container_transform/schema.py", line 38, in <module>
    'required': True,
AttributeError: 'str' object has no attribute 'value'

**Comment by micahhausler** [comment]
Python 2.7 is not supported, please use Python 3.6+
