### ISSUE TITLE
Error container-transform 1.1.5 compose > ECS

### ISSUE THREAD

**Issue by leotada** [micahhausler/container-transform#84]
command:
`container-transform -i compose -o ecs docker-compose.yaml
`

```
Traceback (most recent call last):
  File "/home/leonardo/.local/bin/container-transform", line 11, in <module>
    load_entry_point('container-transform==1.1.5', 'console_scripts', 'container-transform')()
  File "/home/leonardo/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/leonardo/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/leonardo/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/leonardo/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/leonardo/.local/lib/python3.6/site-packages/container_transform/client.py", line 64, in transform
    output = converter.convert(verbose)
  File "/home/leonardo/.local/lib/python3.6/site-packages/container_transform/converter.py", line 57, in convert
    output_transformer
  File "/home/leonardo/.local/lib/python3.6/site-packages/container_transform/converter.py", line 90, in _convert_container
    output[output_name] = emit_func(ingest_func(container.get(input_name)))
  File "/home/leonardo/.local/lib/python3.6/site-packages/container_transform/compose.py", line 305, in ingest_volumes
    in volumes
  File "/home/leonardo/.local/lib/python3.6/site-packages/container_transform/compose.py", line 306, in <listcomp>
    if self._ingest_volume(volume) is not None
  File "/home/leonardo/.local/lib/python3.6/site-packages/container_transform/compose.py", line 271, in _ingest_volume
    parts = volume.split(':')
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by leotada** [comment]
Probably because this new optional syntax:
```
volumes:
  - type: volume
    source: ./db/etc.dump
    target: /dump/etc.dump
```
